apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Enforcement API App
name: rpe-spring-boot-template
home: https://github.com/hmcts/enforcement-api
version: 0.0.17
maintainers:
  - name: HMCTS HDP Enforcement API team
dependencies:
  - name: java
    version: 5.2.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
